### ISSUE TITLE
Safe Area Bottom Inset

### ISSUE THREAD

**Issue by fatemave** [naru-jpn/BottomSheetController#1]
Hi, I apologize for my bad english.

The problem itself should be clear from the screenshot.

Even if the content is nailed to the super view in the controller transmitted during the initialization of the BottomSheetController, this content is nailed to the Safe Area

![photo_2021-06-16 16 42 45](https://user-images.githubusercontent.com/33780791/122229997-ea4f2f00-cec1-11eb-99c1-6acfa2915802.jpeg)

**Comment by naru-jpn** [comment]
@fatemave 
Hi, thanks your feedback :)
I cannot decide which your problem is caused by this library or your configuration of auto layout.

I recommend you to try to edit example project contained this repository and check to represent same problem or not.
