### ISSUE TITLE
Incompatible with UIHostingController. 

### ISSUE THREAD

**Issue by ghost** [naru-jpn/BottomSheetController#2]
Nice bottom sheet - but doesn't properly calculate heights. Missing a lot of features like drag gestures etc.

**Comment by naru-jpn** [comment]
Thanks your feedback 🌟 
I'm glad if you send me pull request with new feature or add features by fork this repository :)

**Comment by naru-jpn** [comment]
I think probably you can use UIHostingController as embeded child view controller.
Please create new issue with source code if library cannot work.
